spring.application.name=events-service
spring.data.mongodb.uri=mongodb+srv://saranyasenthil4688_db_user:1mlebSZlvInX94zm@cluster0.ml9kxjs.mongodb.net/
spring.data.mongodb.database=eventdb
server.port=${PORT:8080}